### ISSUE TITLE
publish container images

### ISSUE THREAD

**Issue by axel7083** [containers/ai-lab-recipes#133]
The following images would be interesting to have available to a registry

- [x] models/convert_models 
> Required by https://github.com/containers/podman-desktop-extension-ai-lab/issues/542

- [x] model_servers/llamacpp_python/cuda
- [x] model_servers/llamacpp_python/vulkan

**Comment by sallyom** [comment]
I'll add them to the workflows!

**Comment by sallyom** [comment]
for the cuda & vulkan, I'm not sure we'll have the disk space necessary in the default actions runners but I'll try - I'll start with only x86 (I think cuda is x86 compatible only, not sure about vulkan)

**Comment by sallyom** [comment]
pushed & added to gh actions nightly publish with [#165](https://github.com/containers/ai-lab-recipes/pull/165)
* `quay.io/ai-lab/model-converter:latest` for arm64, amd64 
* `quay.io/ai-lab/llamacpp-python:latest` arm64, amd64
* `quay.io/ai-lab/llamacpp-python-vulkan:latest` arm64
* `quay.io/ai-lab/llamacpp-python-cuda:latest` amd64
