### ISSUE TITLE
Cannot integrate audio_to_text in AI Lab

### ISSUE THREAD

**Issue by jeffmaury** [containers/ai-lab-recipes#219]
path is incorrect as the context dir is audio_to_text

See
https://github.com/containers/ai-lab-recipes/blob/cd6730d6033c448d61568702780acbd9fa1e8d37/recipes/audio/audio_to_text/builds/Containerfile#L3

**Comment by MichaelClifford** [comment]
Can you try this again with the most up to date code. 

Context dir is now `app` where the requirements file is.

```
 - name: whispercpp-app
      contextdir: app
      containerfile: app/Containerfile
```

**Comment by jeffmaury** [comment]
Replicating here as I got no answer on Slack:

Seems recent changes in the recipes repos make them incompatible with AI Lab and I need to input: in ai-lab.yaml there is 2 information for the build contextdir and containerFile. AI Lab will convert contextdir to an absolute path but will pass containerFile as is to podman so my understanding is that it is processed as a path relative to the contextdir. But it seems contextdir is repeated into the containerFile: see [https://github.com/containers/ai-lab-recipes/blob/c0f800fdc332a904910eb78f7871b051[…]f40ebbb/recipes/natural_language_processing/chatbot/ai-lab.yaml](https://github.com/containers/ai-lab-recipes/blob/c0f800fdc332a904910eb78f7871b0511f40ebbb/recipes/natural_language_processing/chatbot/ai-lab.yaml#L19)
WDYT ?
