### ISSUE TITLE
Error when running auto_to_text recipe in AI Lab with the provided audio file

### ISSUE THREAD

**Issue by jeffmaury** [containers/ai-lab-recipes#244]
Here is the error in the client application:

![image](https://github.com/containers/ai-lab-recipes/assets/695993/178d04e0-77b3-4bde-9af6-7b010baed402)

**Comment by MichaelClifford** [comment]
Can you share the logs of your model server?

**Comment by jeffmaury** [comment]
```
whisper_init_from_file_with_params_no_state: loading model from '/ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU buffer size =   487.20 MB
whisper_model_load: model size    =  487.01 MB
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
```

**Comment by jeffmaury** [comment]
I think I got the issue: when run in AI Lab, the MODEL_ENDPOINT is http://localhost:8001 (as AI Lab only deals with IP and port) and thus the inference suffix is missing. A small change in the python file would adapt

**Comment by MichaelClifford** [comment]
So change  `podman run ... -e MODEL_ENDPOINT=http://10.88.0.1:8001/inference audio`
to something like
`podman run ... -e HOST=10.88.0.1 -e PORT=8001 audio`

**Comment by jeffmaury** [comment]
> So change `podman run ... -e MODEL_ENDPOINT=http://10.88.0.1:8001/inference audio` to something like `podman run ... -e HOST=10.88.0.1 -e PORT=8001 audio`

Yes but that's not enough as AI Lab will set MODEL_ENDPOINT to http://localhost:8001 so the URL used should be somelink like ${MODEL_ENDPOINT}/inference in the Python file

**Comment by MichaelClifford** [comment]
https://github.com/containers/ai-lab-recipes/blob/226a51f51b4e0ffaf11cb38b076d20e147be8086/recipes/common/Makefile.common#L156

Here we include the `/v1` route as part of the `MODEL_SERVICE_ENDPOINT`.

as well as here: 
https://github.com/containers/ai-lab-recipes/blob/226a51f51b4e0ffaf11cb38b076d20e147be8086/recipes/natural_language_processing/chatbot/app/chatbot_ui.py#L12-L13

Do none of these work with AI Lab?

**Comment by jeffmaury** [comment]
> https://github.com/containers/ai-lab-recipes/blob/226a51f51b4e0ffaf11cb38b076d20e147be8086/recipes/common/Makefile.common#L156
> 
> Here we include the `/v1` route as part of the `MODEL_SERVICE_ENDPOINT`.
> 
> as well as here:
> 
> https://github.com/containers/ai-lab-recipes/blob/226a51f51b4e0ffaf11cb38b076d20e147be8086/recipes/natural_language_processing/chatbot/app/chatbot_ui.py#L12-L13
> 
> Do none of these work with AI Lab?

I think they are working because AI Lab sets MODEL_ENDPOINT and not MODEL_SERVICE_ENDPOINT 😡

**Comment by MichaelClifford** [comment]
So then they've all been using the default.

How do we want to go about applying this fix? Is it something that can change in AI Lab or do we need to update all the recipes?

**Comment by jeffmaury** [comment]
> So then they've all been using the default.
> 
> How do we want to go about applying this fix? Is it something that can change in AI Lab or do we need to update all the recipes?

My proposition, because current situation is a mess, is to change to variable name to MODEL_BASE_ENDPOINT (only http://host:port) 
1. Fix recipes
2. Fix AI lab

WDTY ?

**Comment by MichaelClifford** [comment]
OK, I can apply these changes here: 

But, MODEL_BASE_ENDPOINT or MODEL_SERVICE_ENDPOINT?
