### ISSUE TITLE
Bad build instruction in the audio_to_text recipe

### ISSUE THREAD

**Issue by jeffmaury** [containers/ai-lab-recipes#245]
This would lead to:

`Error: no Containerfile or Dockerfile specified or found in context directory, C:\Users\Jeff\work\src\github.com\containers\ai-lab-recipes\model_servers\whispercpp: Le fichier spécifié est introuvable.
`
https://github.com/containers/ai-lab-recipes/blob/96555a1a8dd517b499933b66ba09ac4a248a0bb6/recipes/audio/audio_to_text/README.md?plain=1#L53

**Comment by Gregory-Pereira** [comment]
Makefile works to builds this, docs issue. Try `make build`. Docs issue

**Comment by rhatdan** [comment]
The current docs says 
podman build -t whispercppserver app/
