### ISSUE TITLE
Release coordination for release `1.0` 

### ISSUE THREAD

**Issue by Gregory-Pereira** [containers/ai-lab-recipes#262]
We will be releasing version `1.0` to matchup with Podman Desktop AI Lab.
Release Date: Wednesday, March 17th 

Release Criteria:

- [ ] Brief change log or summary of issues tackled and new features
    - [ ] (OPTIONAL): A comparison of where we are in relation to the Podman Desktop team
- [ ] A commit is made to trigger every workflow in the repo with tests passing
- [ ] Potentially switch to granite mode by default, if it is released?

...
Thoughts @lmilbaum @sallyom @MichaelClifford @rhatdan ?

**Comment by lmilbaum** [comment]
@Gregory-Pereira Thank you so much for crafting this issue (and the others). I'd like to suggest that the release process uses the GitHub releases feature. At the moment it can be done manually but for the future, it can be automoated.
The other suggestion I have is to setup an automation which enforces adding a release note and eventually grabbing all the release notes when releasing.

**Comment by MichaelClifford** [comment]
Close as v1.0.0 is out.
