### ISSUE TITLE
feat(audio_to_text): convert audio to the expected format

### ISSUE THREAD

**Issue by axel7083** [containers/ai-lab-recipes#280]
As raised by @lstocchi in https://github.com/containers/podman-desktop-extension-ai-lab/pull/869#pullrequestreview-2005320708 user may try to use some format which are not compatible.

As `ffmpeg` is available, the `whisper_client.py` could check for the format of the source audio and convert it to the expected format before sending it.

cc @MichaelClifford

**Comment by MichaelClifford** [comment]
Similar to https://github.com/containers/ai-lab-recipes/issues/64.  wIll close 64 in favor of this one.
