### ISSUE TITLE
Typo in image name

### ISSUE THREAD

**Issue by jeffmaury** [containers/ai-lab-recipes#288]
See 
https://github.com/containers/ai-lab-recipes/blob/53af15ba0504b05ffa16118cd953a122f66db5b2/CONTRIBUTING.md?plain=1#L53

Also
https://github.com/containers/ai-lab-recipes/blob/53af15ba0504b05ffa16118cd953a122f66db5b2/recipes/natural_language_processing/chatbot/ai-lab.yaml#L18

**Comment by rhatdan** [comment]
Please open a PR?

**Comment by Gregory-Pereira** [comment]
Moved to: #292

**Comment by Gregory-Pereira** [comment]
Some unresolved references also in #301

**Comment by Gregory-Pereira** [comment]
This is resolved.
