### ISSUE TITLE
update descriptions of recipes

### ISSUE THREAD

**Issue by vrothberg** [containers/ai-lab-recipes#297]
The AI Lab extension displays the descriptions of the recipes which at the present are quite repetitive:

- They all start with "This is a[n] ..."
- All claim it's a "demo application" which doesn't sound fit for production
- I'd prefer a short description of the use cases.  For instance, "Summarizer: Summarize text files in a web front end." (or something similar). 

![Screenshot 2024-04-22 at 09 47 35](https://github.com/containers/ai-lab-recipes/assets/11679875/dc4ec51f-26b3-4382-955d-6f2165067193)

**Comment by slemeur** [comment]
+1

**Comment by vrothberg** [comment]
Opened https://github.com/containers/ai-lab-recipes/pull/298
