### ISSUE TITLE
link model instead of `wget`

### ISSUE THREAD

**Issue by cgwalters** [containers/ai-lab-recipes#3]
re https://github.com/MichaelClifford/locallm/blob/a82ac930d2905ad390a0fd3fcb3ade5a2319bde7/Containerfile-rh#L6-L7

First there's no reason to install `wget` - we already have `curl`.

But even better, I think we want to use `COPY --link` here, as is recommended by e.g. https://github.com/depot/depot.ai#usage

**Comment by MichaelClifford** [comment]
Thanks for the issue @cgwalters! :) We can definitely make that change. Also, there are still a few other outstanding updates that need to be added to this repo to fully reflect what was in the demo. Hoping to get the changes pushed by EOD tomorrow.    

cc  @sallyom

**Comment by cgwalters** [comment]
I've now realized that podman/buildah don't implement `COPY --link`, which is unfortunate.
