### ISSUE TITLE
Swap default model from mistral to granite-7b-lab

### ISSUE THREAD

**Issue by Gregory-Pereira** [containers/ai-lab-recipes#311]
Summit is coming, and with it will be information tying the instructlab models to our organization. We should be using our own tools and assets, so we should swap over to using our default model of `instructlab/granite-7b-lab`. This should be referenced in all our documentation as well as our actual MS / recipes.

Still have yet to hear thoughts about this from @rhatdan @sallyom @lmilbaum

**Comment by MichaelClifford** [comment]
I have run both `instructlab/granite-7b-lab` and `instructlab/merlinte-7b-lab` with the main branch build of llamacpp_python server using the `MODEL_CHAT_FORMAT=openchat" for both the chat application and summarizer (the only two recipes on AI Lab where we'd make this change.    

I can confirm that both recipes work with both models.

**Comment by MichaelClifford** [comment]
issue to get these models included in the AI Lab model catalog https://github.com/containers/podman-desktop-extension-ai-lab/issues/979

**Comment by rhatdan** [comment]
Can you open a PR to change the default to use granite-7b-lab?

**Comment by Gregory-Pereira** [comment]
Closing as this is dealt with in #350

**Comment by devop-mmcgrath** [comment]
Can anyone confirm this also means Granite will show up in the list of models?  I saw a demo earlier today and noticed it was missing from Models -> all list.

**Comment by MichaelClifford** [comment]
@devop-mmcgrath Yeah, we have granite in our model list, and its also propagated into the AI Lab UI. 

https://github.com/containers/ai-lab-recipes/tree/main/models

<img width="931" alt="Screenshot 2024-05-03 at 11 04 40 AM" src="https://github.com/containers/ai-lab-recipes/assets/4494906/66f9b0d6-d6a7-4fef-8a71-c2e4233b86cc">
