### ISSUE TITLE
Request for optional SSHKEY make variable

### ISSUE THREAD

**Issue by danmcp** [containers/ai-lab-recipes#399]
Re: https://github.com/stefwalter/drama-llama/blob/main/1-herd/Containerfile#L3

cc @kwozyman

**Comment by rhatdan** [comment]
Should we make SSHKEY a snippet and allow users to request it.  Seems like it should be treated as an alternative to cloud-init.
Perhaps we could add something like

INCLUDES=sshkey,cloud-init and other Containerfile snippets.

https://gitlab.com/bootc-org/examples.git

**Comment by rhatdan** [comment]
@cgwalters WDYT?

**Comment by ivanbaldo** [comment]
It's not good to have allowed ssh keys stored in images, they should be injected dynamically by cloud-init or other means depending on the platform...

**Comment by rhatdan** [comment]
Cloud-init does not work when installing directly to physical systems.

SSH_PUBKEY is now available as a Makefile option.
