### ISSUE TITLE
The notation "the application can be accessed at http://localhost:8501."  confuses beginners

### ISSUE THREAD

**Issue by tnk4on** [containers/ai-lab-recipes#486]
The README for the recipe includes the following (e.g. Chatbot)
`Once the Pod and its containers are running, the application can be accessed at `http://localhost:8501`. `
https://github.com/containers/ai-lab-recipes/blob/d6fd60a028476bb14e579712b5b4db0d47498443/recipes/natural_language_processing/chatbot/README.md?plain=1#L53

However, applications deployed through the Podman AI Lab will be assigned a random port.
```
% podman ps
CONTAINER ID  IMAGE                                                                    COMMAND     CREATED         STATUS                   PORTS                                             NAMES
222be55abd5a  localhost/podman-pause:5.1.0-dev-9697a5f08-1713225600                                13 minutes ago  Up 13 minutes            0.0.0.0:59760->8001/tcp, 0.0.0.0:59761->8501/tcp  77e981ae29d6-infra
0a846547d16b  sha256:645eb2bf6e46d0eba16b2b43e9f334e695fd955160eb556521497ed431a3e2b5              13 minutes ago  Up 13 minutes (healthy)  0.0.0.0:59760->8001/tcp, 0.0.0.0:59761->8501/tcp  streamlit-chat-app-podified-1715099346227
ac396584c61b  sha256:6ee8ed181c3764a36096361c6c995c1303d0c9b32bb1b300f44a5f191d82804d              13 minutes ago  Up 13 minutes (healthy)  0.0.0.0:59760->8001/tcp, 0.0.0.0:59761->8501/tcp  llamacpp-server-podified-1715099346227
```

It is also advisable to add instructions to select an `Open AI App` icon.
![Screenshot 2024-05-08 at 1 49 37](https://github.com/containers/ai-lab-recipes/assets/54387703/c76a3579-9031-4117-8e48-fb8790a2ef2d)

**Comment by rhatdan** [comment]
@MichaelClifford PTAL

**Comment by MichaelClifford** [comment]
@tnk4on I can see why that is confusing. I will update the docs to add some clarity. But in short, if you are following the README instructions and using `podman kube play build/chatbot.yaml` to deploy the chatbot then `:8501` is the default port.
