### ISSUE TITLE
Lots of 404 when running playground

### ISSUE THREAD

**Issue by lstocchi** [containers/ai-lab-recipes#52]
@MichaelClifford i see a lot of calls fialing wiht 404. Is it expected?
![image](https://github.com/redhat-et/locallm/assets/49404737/8fba5b5c-9f72-4a7d-9cf8-6dfe465075ec)

**Comment by MichaelClifford** [comment]
Is the playground working otherwise @lstocchi ?

But no I would not expect to see this output on all those different ports. 

Can you add some more context of what you are doing to produce these logs?

**Comment by lstocchi** [comment]
The playground was working fine bc i was testing the chatbot and it responded correctly.
Now I tried to look at the logs of the model service when using the summarizer (i was testing https://github.com/redhat-et/locallm/pull/53) and it doesn't happen. SO not sure if it's a problem with the chatbot or the modelservice check fixes something.
I'll try again after we merge some PRs here like #41 and i'll update this issue if i see it again.

**Comment by MichaelClifford** [comment]
the model service check should not really affect the playground at all. Those changes are only in the ai_application code. 

This looks to me like something is trying to hit the model service but giving it bad URLs. Is there anything else in the way the playground is run within AI-studio that would be sending GET requests to it?

**Comment by lstocchi** [comment]
Not able to replicate after switching ai-studio to the new langchain apps. Maybe some PR merged in the meantime fixed it🤷‍♂️
