### ISSUE TITLE
chatbot recipe broken

### ISSUE THREAD

**Issue by jeffmaury** [containers/ai-lab-recipes#546]
Got this error:

![image](https://github.com/containers/ai-lab-recipes/assets/695993/e7bd7cb7-b3e7-4572-be3f-13e9cf61b523)

From main branch:

- `make quadlet`
- `podman play kube build/chatbot.yaml`

**Comment by rhatdan** [comment]
@sallyom PTAL

**Comment by lmilbaum** [comment]
Are you aware if there is a test in place which identifies this problem? If not, would it be possible to start mitigating it with implementing a test which can be invoked in CI?
