### ISSUE TITLE
Add a recipe that works with function calling models

### ISSUE THREAD

**Issue by lstocchi** [containers/ai-lab-recipes#562]
In podman desktop ai lab we are planning to add function calling models support -> https://github.com/containers/podman-desktop-extension-ai-lab/issues/1116

We would need a recipe + a list of recommended models to work with

**Comment by axel7083** [comment]
Depends on https://github.com/containers/ai-lab-recipes/issues/601

**Comment by rhatdan** [comment]
#601 merged, can we close this?

**Comment by lstocchi** [comment]
@rhatdan no. This issue is related to the need to have something similar to the chatbot/rag recipe. So we can add it to ai-lab extension. 
The user downloads the recipe, play with it, check the code how to rewrite a similar app ....

**Comment by axel7083** [comment]
To create a recipe providing function calling, we have the following requirements:

- https://github.com/abetlen/llama-cpp-python/pull/1637
- https://github.com/abetlen/llama-cpp-python/pull/1509
 
I opened https://github.com/abetlen/llama-cpp-python/issues/1636 which should be fixed https://github.com/abetlen/llama-cpp-python/pull/1637

**Comment by axel7083** [comment]
I made some experiments locally with the amazing [Instructor](https://jxnl.github.io/instructor/) library and here are some demos I made using llama-cpp-python 0.83 (any version above crashes)

# Instructor library 

## Information extraction

Given an unstructured text, return a python model.

https://github.com/user-attachments/assets/daca3dd9-3997-4a64-a414-78895754b9e3

A basic [pydantic](https://docs.pydantic.dev/latest/) model provided, the instructor will translate the llm response to the model provided, with validation etc.

## Single text classification 

https://github.com/user-attachments/assets/5372be34-5b52-4af4-b4b2-a6318ca56d8c

Given an enum and a text, got the enum value as result. Allowing basic single text classification.

## Multi text classification

https://github.com/user-attachments/assets/befece89-714d-4d77-a3fb-48a25bf86afe

We can request multiple values as result, allowing to get a multi-classification.

# Function calling

The function calling need a bit of manual change, as we need https://github.com/abetlen/llama-cpp-python/pull/1509 applied, and some adjustment to be able to uses the `functionary-v2.5`[^1] model.

https://github.com/user-attachments/assets/61f76544-e47f-4f28-a194-e0be29cf2b28

Thoses example are took from the llama-cpp-python repository[^2]

[^1]: https://huggingface.co/meetkai/functionary-small-v2.5-GGUF/tree/main
[^2]: https://github.com/abetlen/llama-cpp-python/blob/main/examples/notebooks/Functions.ipynb
