### ISSUE TITLE
add memory to rag and chat applications

### ISSUE THREAD

**Issue by MichaelClifford** [containers/ai-lab-recipes#67]
Both `chat_langchain` and `rag_langchain` do not have memory components. Meaning, that you cannot ask follow up questions during a chat session. 

We should add the a chat memory component that allows for asking follow up questions. It should also gracefully handle the case in which the chat history exceeds the models context window.

**Comment by Gregory-Pereira** [comment]
Closing this issue as it was resolved in #127.
