### ISSUE TITLE
Restore Readme for the recipes 

### ISSUE THREAD

**Issue by slemeur** [containers/ai-lab-recipes#84]
With the latest changes on the recipes, the readme are not providing the same level of details.

Now: https://github.com/redhat-et/locallm/blob/main/summarizer-langchain/README.md
Before: https://github.com/redhat-et/locallm/blob/5ff3767ff3e265a917a4f604211557d2511d41b4/summarizer/README.md 

We would like to get back to the previous version of the content, aligned with the latest changes.

**Comment by MichaelClifford** [comment]
@slemeur I've updated the relevant README's and have closed this issue.
